config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :books
  get 'books/status'
  
  resources :search_status
  resources :rentals, only: [:create, :update]
  resource :isbn
  resource :state_to_ordered
  resource :takeout
  resources :searches
  resources :now_order
  resources :users, only: [:index]
 
 root 'books#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id                                     :integer          not null, primary key
#  author                                 :string
#  borrower                               :string
#  comment                                :text
#  group                                  :string
#  image                                  :string
#  isbn                                   :string
#  price                                  :integer
#  published_at                           :date
#  publisher                              :string
#  registrator                            :string
#  status                                 :string
#  summary                                :text
#  title                                  :string
#  created_at                             :datetime         not null
#  updated_at                             :datetime         not null
#  google_books_api_id                    :string
#  group_id                               :bigint
#  rental_user_id(本を借りているユーザー) :bigint
#  user_id                                :bigint
#
# Indexes
#
#  index_books_on_group_id        (group_id)
#  index_books_on_rental_user_id  (rental_user_id)
#  index_books_on_user_id         (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (group_id => groups.id)
#  fk_rails_...  (rental_user_id => users.id)
#  fk_rails_...  (user_id => users.id)
#
class Book < ApplicationRecord
    mount_uploader :image, ImageUploader
    has_many :rentals, class_name: "Rental"
    has_many :rental_users, through: :rentals, source: :user 
    belongs_to :user
    belongs_to :group
    validates :isbn, uniqueness: true
    scope :now_rentals, -> do
        eager_load(:rentals).where(rentals: {returned: false})
      end 
    
    def rental_user
        not_returned_rental = rentals.where(returned: false).first
        not_returned_rental&.user
    end

    def now_rental?
        rentals.now_rental.present?
    end 
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.where(status: "購入済")
    .or(Book.where(status: ""))
    .page(params[:page]).per(10).reverse_order#ページング表示#10項目ごとに表示#最新順
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @rental = Rental.all
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end



  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: '書籍情報は正常に登録されました.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: '書籍情報は正常に更新されました.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: '書籍情報は正常に削除されました.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book)
      .permit(
        :image, :title, :author, 
        :publisher, :published_at, 
        :registrator,:summary,
        :isbn, :status, :comment
      ).merge(user_id: current_user.id,group_id: current_user.group_id)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(book) do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :表紙イメージ %>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :タイトル %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :著者 %>
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :出版社 %>
    <%= f.text_field :publisher%>
  </div>

  <div class="field">
    <%= f.label :発行年 %>
    <%= f.date_select :published_at, use_month_numbers: true, start_year: 1950, end_year: Time.now.year, date_separator: '/' %>
  </div>

  <div class="field">
    <%= f.label :分類 %>
    <%= f.select :group_id, Group.all.map { |group| [group.name, group.id] } %>
  </div>

  <div class="field">
    <%= f.label :概要 %>
    <%= f.text_area :summary %>
  </div>

  <div class="field">
    <%= f.label :ISBN %>
    <%= f.text_field :isbn %>
  </div>

  <div class="field">
    <%= f.label :注文状況 %>
    <%= f.select :status, [["購入済", "購入済"], ["未購入", "未購入"]], include_blank: "選択して下さい" %>
  </div>
  
  <div class="field">
    <%= f.label :コメント %>
    <%= f.text_area :comment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/_table.html.erb
<table class="table table-bordered">
  <thead>

    <tr>
      <th class="text-center">表紙</th>
      <th class="text-center">タイトル</th>
      <th class="text-center">著者</th>
      <th class="text-center">出版社</th>
      <th class="text-center">発行年</th>
      <th class="text-center">分類</th>
      <th class="text-center">コメント</th>
      <th class="text-center" colspan="4" >操作</th>
      <th class="text-center">所有者</th>
      
    </tr>
  
  </thead>

  <tbody>
    <% books.each do |book| %>
      <tr>
        <% if book.image&.url %>
        <td><%= image_tag book.image&.url, :size  => '60x80'%></td>
        <% end %>
        <td class="text-center align-middle"><%= book.title %></td>
        <td class="text-center align-middle"><%= book.author %></td>
        <td class="text-center align-middle"><%= book.publisher %></td>
        <td class="text-center align-middle"><%= book.published_at %></td>
        <td class="text-center align-middle"><%= book.group&.name %></td>
        <td class="text-center align-middle"><%= book.comment %></td>
        <td class="text-center align-middle">
          <% if book.now_rental? %> <%# 本に紐付いているrental_usersのうち、returnedがfalseのデータが存在する場合 %>
            <% if book.rental_user==current_user %>
              <%= link_to '返却', rental_path(id: book.rentals.now_rental.first.id), method: :patch, data: { confirm: '書籍の返却を行いますか？' } %>
            <% else %><%# rental_userが存在するがcurrent_userと一致しない（他のアカウントで書籍が借りられている）%>
            <span >貸出中</span>
            <% end %>
          <% elsif book.status=="未購入"%><%#未購入品は貸出できない %>
          <span></span>
          <% else %>
          <%= link_to '貸出', rentals_path(id: book.id), method: :post, data: { confirm: '書籍の貸出を行いますか？' }%>
          <% end %>
        </td>
        <td class="text-center align-middle"><%= link_to '詳細', book %></td>
        <td class="text-center align-middle"><%= link_to '編集', edit_book_path(book) %></td>
        <td class="text-center align-middle"><%= link_to '削除', book, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %></td>
        <td class="text-center align-middle"><%= book.rental_user&.name %></td>
      </tr>
    <% end %>
    
  </tbody>
</table>
<%= paginate books %>

app/views/books/edit.html.erb
<h1>編集</h1>

<%= render 'form', book: @book %>

<%= link_to '詳細', @book %> |
<%= link_to '戻る', books_path %>

app/views/books/index.html.erb
<div class="header2">
    <%= link_to '登録(自動)', new_isbn_path %>
    <%= link_to '登録(手動)', new_book_path %>
    <%= link_to '未購入書籍一覧', search_status_index_path %>
    <%= link_to '発注済み書籍一覧', now_order_index_path %>
    <%= link_to '検索', searches_path %>
</div>

<h1>書籍一覧</h1>

<%= render 'table', books: @books %>
<br>

app/views/books/new.html.erb
<div class="header2">
<%= link_to '書籍一覧', books_path%>
<%= link_to '登録(自動)', new_isbn_path %>
<%= link_to '未購入品一覧', search_status_index_path %>
<%= link_to '発注済み書籍一覧', now_order_index_path %>
<%= link_to '検索', searches_path %>
</div>

<h1>登録(手動)</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<div class="header2">
<%= link_to '書籍一覧', books_path%>
<%= link_to '登録(自動)', new_isbn_path %>
<%= link_to '登録(手動)', new_book_path %>
<%= link_to '未購入品一覧', search_status_index_path %>
<%= link_to '発注済み書籍一覧', now_order_index_path %>
<%= link_to '検索', searches_path %>
</div>

<h1>詳細</h1>

<p>
  <strong >表紙イメージ:</strong>
  <%= image_tag @book.image&.url, :size  => '60x80'%>
</p>

<p>
  <strong>タイトル:</strong>
  <%= @book.title %>
</p>

<p>
  <strong >登録者名:</strong>
  <%= @book.user.name %>
</p>

<p>
  <strong>著者:</strong>
  <%= @book.author %>
</p>

<p>
  <strong >出版社:</strong>
  <%= @book.publisher %>
</p>

<p>
  <strong>発行年:</strong>
  <%= @book.published_at %>
</p>

<p>
  <strong>分類:</strong>
  <%= @book.group&.name %>
</p>

<p>
  <strong>概要:</strong>
  <%= @book.summary %>
</p>

<p>
  <strong>Isbnコード:</strong>
  <%= @book.isbn %>
</p>

<p>
  <strong>注文状況:</strong>
  <%= @book.status %>
</p>

<p>
  <strong>コメント:</strong>
  <%= @book.comment %>
</p>

<p>
  <strong>貸し出し履歴:</strong>
  <ul>
  <% @book.rentals.each do |rental|%>
    <li><%= rental.user.name%>  <<%= rental.created_at.to_s(:datetime_jp) %>〜<%= rental.updated_at.to_s(:datetime_jp) %>></li>
  <% end %>
  </ul>
</p>

<%= link_to '編集', edit_book_path(@book) %>
<%= link_to '削除', @book, method: :delete, data: { confirm: '本当にこの書籍情報を削除しますか？' } %>