config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :books
  get 'books/status'
  
  resources :search_status
  resources :rentals, only: [:create, :update]
  resource :isbn
  resource :state_to_ordered
  resource :takeout
  resources :searches
  resources :now_order
  resources :users, only: [:index]
 
 root 'books#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/isbns_controller.rb
class IsbnsController < ApplicationController
    
    def new
        
    end
    
    def create
       
       # response = GoogleBooksAPI.new(params[:isbn]).main
       response = GoogleBooksApiService.new.execute(params[:isbn])
    
       return redirect_to new_isbn_path, notice: 'ISBNコードが存在しません' if response["totalItems"] == 0
        title = response["items"][0]["volumeInfo"]["title"]
        
        if response["items"][0]["volumeInfo"]["authors"]
            author = response["items"][0]["volumeInfo"]["authors"][0]
        else 
            author = nil
        end
        
        if response["items"][0]["volumeInfo"]["imageLinks"]
        image = response["items"][0]["volumeInfo"]["imageLinks"]["smallThumbnail"]
        else
            image = nil
        end
        publisher = response["items"][0]["volumeInfo"]["publisher"]
        
        published_at = response["items"][0]["volumeInfo"]["publishedDate"]
        
        if response["items"][0]["volumeInfo"]["industryIdentifiers"]
            isbn = response["items"][0]["volumeInfo"]["industryIdentifiers"][1]["identifier"]
        end
        
        summary = response["items"][0]["volumeInfo"]["description"]
        
        
        @book = Book.new(
                        title: title,
                        author: author,
                        publisher: publisher,
                        published_at: published_at,
                        status: params[:status],
                        isbn: isbn,
                        summary: summary
                        )
        @book.remote_image_url = image
        @book.user = current_user
        @book.group_id = params[:group_id]
        @book.comment = params[:comment]
        
        if @book.save
            redirect_to new_isbn_path(@book), notice: '書籍情報が正しく登録されました'
            
        else
            redirect_to new_isbn_path, notice: '同一の書籍が既に登録されています'
            
        end
        
    end
end

app/views/isbns/new.html.erb
<div class="header2">
<%= link_to '書籍一覧', books_path%>
<%= link_to '登録(手動)', new_book_path %>
<%= link_to '未購入品一覧', search_status_index_path %>
<%= link_to '発注済み書籍一覧', now_order_index_path %>
<%= link_to '検索', searches_path %>
</div>
<h1>ISBNコードから書籍データを取得</h1>

<%= form_with url: isbn_path do |form| %>
  <%= form.label :isbnコード %>
  <%= form.text_field :isbn %>
<br>
  <%= form.label :分類 %>
  <%= form.select :group_id, Group.all.map { |group| [group.name, group.id] } %>
<br>
  <%= form.label :注文状況 %>
  <%= form.select :status, [["購入済", "購入済"], ["未購入", "未購入"]], include_blank: "選択して下さい" %>
<br>
  <%= form.label :コメント %>
  <%= form.text_area :comment %>
<br>  
  <%= form.submit "登録" %>
  
<% end %>